SELECT TOP (1000) [Id]
      ,[Nombre]
      ,[Eliminado]
  FROM [WorkSyncDB].[dbo].[TipoDeLicencia]

  INSERT INTO dbo.TipoDeLicencia (Nombre, Eliminado)
VALUES
('VACACIONES ANUALES', 0),
('ENFERMEDAD', 0),
('MATERNIDAD', 0),
('PATERNIDAD', 0),
('MATRIMONIO', 0),
('FALLECIMIENTO DE FAMILIAR', 0),
('ESTUDIOS', 0),
('EXAMEN', 0),
('MUDANZA', 0),
('ESPECIAL SIN GOCE DE HABERES', 0),
('ACCIDENTE DE TRABAJO', 0),
('DONACIÓN DE SANGRE', 0),
('ADOPCIÓN', 0),
('ATENCIÓN DE FAMILIAR ENFERMO', 0),
('CAPACITACIÓN', 0),
('CITACIÓN JUDICIAL', 0),
('TRASLADO', 0),
('ESPECIAL CON GOCE DE HABERES', 0),
('GUARDIA MÉDICA', 0),
('SERVICIO MILITAR', 0);